### ISSUE TITLE
Show add button

### ISSUE THREAD

**Issue by sandeeponrails** [Bridgeconn/bib-edit#127]
Show the add button on every verse on hover and while clicking textbox should be open with submit and cancel button. As shown in the call?

**Comment by nbajpai9** [comment]
dynamic headers added

**Comment by sandeeponrails** [comment]
I am unable to see button on hover and that button is directly visible to me. Also while clicking on button textbox doesn't appear.

**Comment by joelthe1** [comment]
Defunct.
