### ISSUE TITLE
Understand the basic flow of Electron Js

### ISSUE THREAD

**Issue by sandeeponrails** [Bridgeconn/bib-edit#129]

**Comment by HimanshuBCS** [comment]
Grasp the Basics of the ElectronJS.
Installed the locally using node package manager & create a applications.

**Comment by HimanshuBCS** [comment]
Exploring the basics of electronjs with creating dummy application.

**Comment by HimanshuBCS** [comment]
Understand the basic flows and integrated with **PouchDB**.

**Comment by joelthe1** [comment]
Defunct.
