### ISSUE TITLE
create simple Student Information System to understand the work of pouchdb and electron

### ISSUE THREAD

**Issue by sandeeponrails** [Bridgeconn/bib-edit#130]

**Comment by sandeeponrails** [comment]
create crud operation:
1. Add student
2. view student
3. display student list
4. update student
5. delete student

**Comment by HimanshuBCS** [comment]
I have to integrate PouchDB with electronJS student information system application.
Added Student need to show in in UI

**Comment by HimanshuBCS** [comment]
I have added view option student for student information system.

**Comment by HimanshuBCS** [comment]
Added DB for the student info & saved data in IndexdDB

**Comment by joelthe1** [comment]
Defunct.
