### ISSUE TITLE
create export to html button with nice look

### ISSUE THREAD

**Issue by sandeeponrails** [Bridgeconn/bib-edit#132]

**Comment by HimanshuBCS** [comment]
I have completed the task for the export to html button & commit the changes locally.
![export_to_html](https://user-images.githubusercontent.com/26620717/34772030-b1401060-f62c-11e7-956f-181301a3ea84.png)

**Comment by HimanshuBCS** [comment]
I have completed the task for the export to html button & commit the changes locally.
![export_to_html](https://user-images.githubusercontent.com/26620717/34772000-8b35647e-f62c-11e7-9dec-31630cee21aa.png)

**Comment by joelthe1** [comment]
Defunct.
