### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/bib-edit#138]
Make changes for UI based on feedback from Donny:
- [x] Make HTML 1-column layout.
- [x] Have verse numbers based on CSS and not hard-coded.
- [x] Make the auto-update default to 'Disabled' in UI.
- [x] In 3x and 4x the verse numbers break to a new line from the adjoining verse text.

**Comment by sandeeponrails** [comment]
Hello Joel,

Make HTML 1-column layout.
 Have verse numbers based on CSS and not hard-coded.
 Make the auto-update default to 'Disabled' in UI.
 In 3x and 4x the verse numbers break to a new line from the adjoining verse text.

all the above issue is resloved and push in the "arabic_issue_fix"  branch
