### ISSUE TITLE
Language Code Dropdown

### ISSUE THREAD

**Issue by binu-alexander** [Bridgeconn/bib-edit#47]

**Comment by megahirt** [comment]
Hi,

Just stumbled upon your project and thought I would mention work we've done recently with a language code picker.  We (SIL software development) just finished a task to automate the creation of a language data index which depends upon several internet sources.  The index is used in our C# picker and our web picker.  This is built via our CI server with a JSON output for web tools.  The C# command line application which generates the index is here: https://github.com/sillsdev/libpalaso/tree/master/LanguageData
The JSON output isn't checked in to the repo at the moment but that will probably change.  Here's the recent one from our CI server that could be helpful to you:
[LanguageDataIndex.json.txt](https://github.com/Bridgeconn/bib-edit/files/748191/LanguageDataIndex.json.txt)

**Comment by joelthe1** [comment]
Hi!
Thank you for that information! We will be looking in to ways to incorporate this in the coming days. Autographa Lite aims to be a desktop-only application which serves all the needs of translators working in fields which may only have intermittent internet access at best. So we could bundle the changes that we see in the language data along with other bug-fixes/features in future updates. We are currently attempting to set-up auto-update feature which would make such changes seamless.

Also, I'm curious how you stumbled upon this page?! Is there anything specific you are looking for. Are there any common interests? I would love to hear your thoughts.

**Comment by joelthe1** [comment]
Added data to application.
