### ISSUE TITLE
selected chapter should be highlighted

### ISSUE THREAD

**Issue by sandeeponrails** [Bridgeconn/bib-edit#83]

**Comment by ayushnig** [comment]
Setting Cookie and fetching the cookie to highlight the selected book.

**Comment by sandeeponrails** [comment]
As i have checked on the branch react_navbar and still  am not able to see the functionality working. I found another issue here as well. When I start app first time and click on the chapter tab and select chapter then book name doesn't appear in the navbar button. Please have a look at this issue.

**Comment by sandeeponrails** [comment]
implemented with mobx
